// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioObjectConfig } from "./AudioObjectConfig";
import type { AudioObjectListConfig } from "./AudioObjectListConfig";

export type AudioMixerStore = {
  schemaVersion: number;
  audioObjects: Array<AudioObjectConfig>;
  audioObjectLists: Array<AudioObjectListConfig>;
};
