// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCompositionConfig } from "./AudioCompositionConfig";

export type AudioCompositionStore = {
  schemaVersion: number;
  audioCompositions: Array<AudioCompositionConfig>;
};
