// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioLoopRegionConfig = {
  enabled: boolean;
  startSeconds: number;
  endSeconds: number | null;
};
