// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioLoopRegionConfig } from "./AudioLoopRegionConfig";
import type { AudioRegionConfig } from "./AudioRegionConfig";

export type AudioObjectConfig = {
  id: string;
  name: string;
  description: string;
  tags: Array<string>;
  filePath: string;
  defaultVolume: number;
  fadeInMs: number;
  fadeOutMs: number;
  playableRegion: AudioRegionConfig;
  loopRegion: AudioLoopRegionConfig;
};
