// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCompositionPlaybackMode } from "./AudioCompositionPlaybackMode";
import type { AudioCompositionTrackSourceKind } from "./AudioCompositionTrackSourceKind";

export type AudioCompositionTrackConfig = {
  id: string;
  sourceKind: AudioCompositionTrackSourceKind;
  sourceId: string;
  volume: number;
  playbackMode: AudioCompositionPlaybackMode;
  fadeInMs: number | null;
  fadeOutMs: number | null;
  randomMinSeconds: number | null;
  randomMaxSeconds: number | null;
  triggerLabel: string | null;
  enabled: boolean;
};
