// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCompositionTrackConfig } from "./AudioCompositionTrackConfig";

export type AudioCompositionConfig = {
  id: string;
  name: string;
  description: string;
  tracks: Array<AudioCompositionTrackConfig>;
};
