// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitiativeParticipantConfig } from "./InitiativeParticipantConfig";

export type InitiativeEncounterConfig = {
  id: string;
  name: string;
  description: string;
  participants: Array<InitiativeParticipantConfig>;
};
