// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitiativeParticipantRole } from "./InitiativeParticipantRole";

export type InitiativeParticipantConfig = {
  id: string;
  name: string;
  role: InitiativeParticipantRole;
  initiativeModifier: number;
  armorClass: number | null;
  hitPoints: number | null;
  notes: string;
};
