// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SceneConfig = {
  id: string;
  name: string;
  description: string;
  notes: string;
  audioCompositionId: string | null;
  initiativeEncounterId: string | null;
};
