// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneConfig } from "./SceneConfig";

export type SceneStore = { schemaVersion: number; scenes: Array<SceneConfig> };
