// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionConfig } from "./SessionConfig";

export type SessionStore = { schemaVersion: number; sessions: Array<SessionConfig> };
