// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionConfig = {
  id: string;
  name: string;
  description: string;
  notes: string;
  sceneIds: Array<string>;
  activeSceneId: string | null;
};
